### ISSUE TITLE
Migrate issues from SourceForge

### ISSUE THREAD

**Issue by jamesbassett** [super-csv/super-csv#1]
Migrate any outstanding issues from SourceForge.

* **Bugs**: http://sourceforge.net/p/supercsv/bugs
* **Feature Requests**: http://sourceforge.net/p/supercsv/feature-requests/

**Comment by jamesbassett** [comment]
@kbilsted I've migrated all the issues from SourceForge that I consider valid.  Take a look and let me know if there's any left you think should be copied across - otherwise I'll just close them all off. 

I've also locked it down so no new bugs/feature requests can be raised via SourceForge, but I'll leave everything there for historical purposes (especially as the website release notes refer to those old issues).

**Comment by kbilsted** [comment]
great - how about

https://sourceforge.net/p/supercsv/bugs/52/
https://sourceforge.net/p/supercsv/feature-requests/42/
https://sourceforge.net/p/supercsv/feature-requests/33/ (2 issues.. one being a config for interning strings)
https://sourceforge.net/p/supercsv/feature-requests/29/

what do you think about including these?

**Comment by jamesbassett** [comment]
I closed 33 (it should have been closed already as it was solved), and added the rest (including some others you didn't mention).

So now SourceForge will just be used for:
* Historical purposes (release notes still point to old SF bugs/features)
* Downloads (people are still going to download from SF, so may as well upload the distribution there as well...for now)
* Donation URL (PayPal link breaks Maven site, so using SF donation URL as redirect still)
* Redirecting old website URLs (old website pages redirect to GitHub pages so links on StackOverflow etc still work - this even includes the javadoc!)

**Comment by kbilsted** [comment]
great job!
