### ISSUE TITLE
Not implemented StringCellProcessor with ParseZoneId/ParseDuration/ParsePeriod

### ISSUE THREAD

**Issue by mygreen** [super-csv/super-csv#100]
Parsing CellProcessor for Java8 classes,  should be implemented interface ``StringCellProcessor`` with ``ParseZoneId/ParseDuration/ParsePeriod``.

then, cannot building CellProcessor with trim.

```java
// compile error.
CellProcessor cp = new Trim(new ParseZoneId());
```

**Comment by jamesbassett** [comment]
Also applies to the joda module

**Comment by kbilsted** [comment]
@mygreen  it would be great if you can do a PR for us

**Comment by jamiebaggott** [comment]
I think that this issue can be closed now, or is more work required?

**Comment by kbilsted** [comment]
:+1:
