### ISSUE TITLE
document the new Preference to distinguish between null and empty columns 

### ISSUE THREAD

**Issue by kbilsted** [super-csv/super-csv#102]
The code from https://github.com/super-csv/super-csv/pull/84 was merged in without changes to the documentation. We need the documentation

**Comment by ash211** [comment]
@kbilsted I took a first crack at this in the above PR -- this is the last thing blocking the 2.5.0 release and I'd like to get that out shortly so I can more easily take advantage of the quote escape parsing contribution I made a few months ago.

Once we get this merged, can we cut the 2.5.0 release?
