### ISSUE TITLE
Tidy up unit tests for Exception classes

### ISSUE THREAD

**Issue by kbilsted** [super-csv/super-csv#11]
Some of the unit tests print to standard out (the unit tests in `org.supercsv.exception` all use `e.printStackTrace()`). This can be misleading when the stacktraces indicate something might be wrong, but all of the tests pass (because the exception was expected). 

All of those tests should use JUnit's [ExpectedException](http://junit.org/javadoc/latest/org/junit/rules/ExpectedException.html) rule instead.

**Comment by kbilsted** [comment]
Reopened so we remember to use junits expect exception

**Comment by jamesbassett** [comment]
The tests in question were only constructor tests, so the comment regarding ExceptedException wasn't relevant (no exceptions are actually thrown).

**Comment by kbilsted** [comment]
I see you've removed the printing in 7d7bedd99ca49e58ea0dbde3708a75c49f30a64f
