### ISSUE TITLE
how to correct format a long numeric string?

### ISSUE THREAD

**Issue by geosmart** [super-csv/super-csv#110]
I set the header like this

``` java
 CellProcessor[] processors = new CellProcessor[headers.length];
                for (int i = 0; i < processors.length; i++) {
                    processors[i] = new NotNull();
                }
```

and the data ：
`Object[] row=new Object[]{"2984303180499968","john","male"};`

But  the generateed csv file  
treat **long numeric string**(2984303180499968) as **scientific notation**(2.9843E+15) !

how can I define the cell format just like the poi does：`row.createCell(j).setCellValue((String) rowData[j])`

**Comment by geosmart** [comment]
anyone knows?

**Comment by dota17** [comment]
Hi, @geosmart 
Did you encounter this problem by opening the CSV file through execel? 
This problem is not caused by super CSV, but by Excel, because it is normal to open in notpad++. And if you want to avoid this problem, you can use the following methods:
```java
List<Object> row = Arrays.asList(new Object[]{"\t2984303180499968","john","male"})
```
