### ISSUE TITLE
How to find and delete duplicate rows in CSV

### ISSUE THREAD

**Issue by kiranraacharya** [super-csv/super-csv#113]
Please help me to find duplicate rows and delete.

**Comment by ash211** [comment]
Deduplicating data is outside the scope of the super-csv package, which just aims to parse CSVs into a more structured form (Map, List, POJO, etc).  I think this question is better suited for a stackoverflow-style discussion like [this SO post](http://stackoverflow.com/questions/14071791/how-to-remove-duplicate-rows-from-a-csv-file).

**Comment by kbilsted** [comment]
👍
