### ISSUE TITLE
Document Java 8 processors

### ISSUE THREAD

**Issue by jamesbassett** [super-csv/super-csv#118]
The list of Java 8 cell processors [on the website](http://super-csv.github.io/super-csv/cell_processors.html) is a little bit short and [people](http://stackoverflow.com/q/41069953/1068649) don't know what's actually supported.

**Comment by dota17** [comment]
#167 is the PR for fixing this problem. 
Please close, Thanks!

**Comment by kbilsted** [comment]
@dota17  you can autoclose issues if your commit message contains the right information see https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords
