### ISSUE TITLE
Thread safety issue with CsvPreference

### ISSUE THREAD

**Issue by victori** [super-csv/super-csv#127]
Affected version: 2.1.0

Using CsvPreference's predefined static preference instances across multiple writers in different threads will cause unexpected write issues due to the DefaultCsvEncoder reusing its StringBuilder instance while encoding the output.

Workaround: Create a unique CSVPreference for each writer instance

**Comment by dota17** [comment]
Hi, @victori 
What's your problem in using super-csv? Is it the problem that super-csv supports multi-threaded reading and writing?

**Comment by kbilsted** [comment]
@victori static and multi thread may lead to problems when you have mutability. Feel free to make an instance version and leave the static as an option for backward compatibility

**Comment by victori** [comment]
Hey guys,

Yes, that is exactly what I have done, create a new CSVPreference for each instance of the CSV parser. 

I was hoping that the report might nudge for the removal of the static instance since it can lead to subtle ingestion bugs depending how it is used.
