### ISSUE TITLE
Support backslash escaping (configurable escape character)

### ISSUE THREAD

**Issue by jamesbassett** [super-csv/super-csv#14]
Super CSV escapes embedded quotes per [RFC4180](http://super-csv.github.io/super-csv/csv_specification.html), e.g. 

    "This is what ""embedded quotes"" look like"

Some CSV files don't adhere to RFC4180, and use a `\` (backslash) character instead 2 quote characters, e.g. 

    "This is what \"embedded quotes\" look like"

Add an `escapeCharacter` preference (defaults to `quoteCharacter`) that allows for this (with a disclaimer that it makes CSV less portable and doesn't comply with RFC4180.

Originally raised as [Feature Request 42](https://sourceforge.net/p/supercsv/feature-requests/42/) on SourceForge.

**Comment by kbilsted** [comment]
Quote @jamesbassett : you guys might disagree, but I really hate the backslash escaping - so many issues are caused by invalid CSV and this feature only makes the situation worse.

**Comment by ZioberMichal** [comment]
This issue is similar to https://github.com/super-csv/super-csv/issues/79 and related to https://github.com/super-csv/super-csv/issues/77. We should really think about how to implement it properly.

**Comment by nhajratw** [comment]
IMHO -- this should be supported. Regardless of whether it is *right* for backslash escaping in CSV files, the fact is that there are many files that need processing that come in this way generated by third parties, and not supporting it requires people (i.e. me) to switch to a different parser.

**Comment by ash211** [comment]
This would be very helpful -- if SuperCSV intends to support all CSV files, including "near-CSV" files that  don't precisely meet RFC4180, then this is a must.  It's a very common export format for tools that don't adhere to the CSV spec.

**Comment by kbilsted** [comment]
@ash211  are you willing to give it a try at implementing something? Feel free to first discuss the design before the coding

**Comment by jamesbassett** [comment]
waits for Kasper to notice #103........

**Comment by kbilsted** [comment]
As mentioned in https://github.com/super-csv/super-csv/issues/79#issuecomment-221129394 we should make the escaping customized

**Comment by kbilsted** [comment]
@jamesbassett hey I just got up and am at work now (8 am here) so pleeease allow me more time to pick up stuff ;)

**Comment by ash211** [comment]
@kbilsted can you please mark this ticket as Milestone 2.5.0?  Are there other things you won't done besides https://github.com/super-csv/super-csv/issues?milestone=4 before releasing?

**Comment by kbilsted** [comment]
@ash211  thanks.. not sure we have any plans for exactly what goes into 2.5
