### ISSUE TITLE
Write file as plain US-ASCII?

### ISSUE THREAD

**Issue by thanateros** [super-csv/super-csv#140]
I've scoured google for days and cannot find a single example of changing the character set of the generated CSV file.  

I'm using an `ICSVListWriter` to accomplish this, and it saves by default as UTF-8 however the people I send this file to now wish for it be plain-old 8-bit ASCII.

I have a notion that is probably somewhere in `CsvPreference` but have yet to figure it out.

Anyone know how to make is save as ASCII encoding?

**Comment by imkrmgn** [comment]
`utf-8` is compatible with `us-ascii` if it is within the range of ascii. Therefore, you are not in trouble at the moment right?

If you still want to change the character code, you can do as follows.
```
Writer w = java.lang.Files.newBufferedWriter(outfilepath, Charset.forName("US-ASCII"));
ICsvListWriter csvw = new CsvListWriter(w):
```

**Comment by thanateros** [comment]
Thanks!  I implemented that and now I'll see if it works next time I have to generate that file.

**Comment by thanateros** [comment]
Looks like it worked fine; thanks!
