### ISSUE TITLE
Chinese messy code when open with microsoft excel

### ISSUE THREAD

**Issue by liunewshine** [super-csv/super-csv#141]
![image](https://user-images.githubusercontent.com/7698511/39538570-ced9a320-4e6f-11e8-9af7-0e95f7b62a00.png)

notepad++ is ok
![image](https://user-images.githubusercontent.com/7698511/39538593-db074094-4e6f-11e8-9949-012752831301.png)

**Comment by dota17** [comment]
Hello，@liunewshine 
How did this file come about? Can you provide a detailed error scenario (with attachments is best)?

**Comment by dota17** [comment]
Hi, @liunewshine 
You can convert to UTF-8 with BOM format through notpadd++, and then open it through Excel to avoid this problem.

**Comment by kbilsted** [comment]
Not a bug but excel visualisation
