### ISSUE TITLE
Why is the CsvContext class final?

### ISSUE THREAD

**Issue by ptahchiev** [super-csv/super-csv#144]
Hello,
I would like to pass some more information to each of my `CellProcessor`. However I can't extend the `CsvContext` because it is marked as final. Is there a reason for this? Can you make it not final?

**Comment by ptahchiev** [comment]
Any updates on this?

**Comment by kbilsted** [comment]
it could be made non-final. I need to install Java and maven to move on with this. You may also send a PR and we can do it that way around?

**Comment by kbilsted** [comment]
have you seen https://github.com/super-csv/super-csv/issues/47 btw?
