### ISSUE TITLE
CellProcessors for Joda-Time

### ISSUE THREAD

**Issue by jamesbassett** [super-csv/super-csv#15]
Add cell processors for [Joda-Time](http://www.joda.org/joda-time/) classes. They should be in a separate module, e.g. `super-csv-joda`

Originally raised on [SourceForge](https://sourceforge.net/p/supercsv/bugs/56/)

**Comment by kbilsted** [comment]
Yes probably we need a separate submodule in github for this or an entirely new project? with its own maven build etc? Sounds like the later?

**Comment by jamesbassett** [comment]
Nah, I think this should just be another module of Super CSV (like the dozer extension).  I'll take a look at this ticket - shouldn't be too tricky and I think it's quite useful.

**Comment by kbilsted** [comment]
yep... i just havent played with githubs submodules :) but lets do it the way the other modules have been structured.
