### ISSUE TITLE
How to implement no quote mode for all columns?

### ISSUE THREAD

**Issue by tushparmar** [super-csv/super-csv#150]
My requirement is to write all the data without modifying any part of it so I wrote a custom QuoteMode class 

```
import org.supercsv.prefs.CsvPreference;
import org.supercsv.quote.QuoteMode;
import org.supercsv.util.CsvContext;

public class NoQuoteMode implements QuoteMode
{
	@Override
	public boolean quotesRequired(String csvColumn, CsvContext context, CsvPreference preference)
	{
		return false;
	}
}
```

When I generate CSV quotes are applied to column data with non-alphanumeric or special characters.

**Comment by dota17** [comment]
Hi, @tushparmar 
What does this question mean? Can you describe the specific scene?

**Comment by kbilsted** [comment]
I think he posted it for future use for others to enjoy. I'm thus closing it
