### ISSUE TITLE
I just downloaded the zip file  and i got a virus warning  found a trojan in the zip file

### ISSUE THREAD

**Issue by immaballin247** [super-csv/super-csv#153]
I just downloaded the zip file  and i got a virus warning  found a trojan in the zip file

![Screenshot 2019-04-13 19 52 34](https://user-images.githubusercontent.com/8071437/56087810-69023a80-5e27-11e9-8a8a-537b8a4fafcc.png)
picture of the warning I got

**Comment by kbilsted** [comment]
Many thanks for reporting. 

Please explain the download steps and url so i can look into this

**Comment by goxr3plus** [comment]
Maybe he downloaded it from https://en.softonic.com/ (troll face)

**Comment by kbilsted** [comment]
Who knows. Closing due to missing information
