### ISSUE TITLE
Super CSV doesn't pass the Turkey Test

### ISSUE THREAD

**Issue by jamesbassett** [super-csv/super-csv#16]
Super CSV doesn't work when your locale is Turkey: reflection fails because it looks for getters/setters in the format: `setİsActive /getİsActive` (not the capital I is not normal).

There's so many places in the code where this could be an issue that I'm reluctant to attempt to make Super CSV [pass the Turkey Test](http://www.moserware.com/2008/02/does-your-code-pass-turkey-test.html) - I don't think Dozer would pass this test either.  But if this ticket gets enough love then we could look at it.

Originally raised on [SourceForge](https://sourceforge.net/p/supercsv/bugs/58/)

**Comment by ZioberMichal** [comment]
Hi @jamesbassett,
    this problem is really interesting and I wanted to simulate it on my computer. I have created new profile in POM configuration (in the same way you have created for Danish and English):
```xml
		<profile>
			<!-- enable this profile to run tests with a Turkish locale -->
			<id>turkishLocale</id>
			<properties>
				<surefireArgs>-Duser.country=TR -Duser.language=tr</surefireArgs>
			</properties>
		</profile>
```
After that I have run test with `-PturkishLocale` profile but every test passed. I have even added one property: `isRegistered` to `org.supercsv.mock.ReflectionBean` and some test methods but everything works pretty good. Are you sure that this project does not pass Turkish test? 

... or maybe I've just made a mistake somewhere.

Could you push some tests which do not pass when Turkish locale is enabled?

Best regards,
Michał

**Comment by ZioberMichal** [comment]
I tried to debug tests when Turkish locale is selected and thats true - for isXxx fields app converts "i" to lower case using default locales and for Turkish one `setİsXxx /getİsXxx` appears but this is irrelevant as long as we use `equalsIgnoreCase` method to compare String-s. This method knows how to handle cases like this. It appear that `ReflectionUtils` uses `equalsIgnoreCase` in "sensitive" pieces of code (Good job!).

To avoid situations like this it is recommended to use: `toLower/UpperCase(Locale.ENGLISH)`. I tried to find `toUpperCase()` attempts in source code and I found only one! I have replaced it with recommended one and all tests passes under English, German and Turkish locales.

**Comment by ZioberMichal** [comment]
I have noticed that you have 3 build jobs for different locales. I propose to add: turkishLocale.

**Comment by kbilsted** [comment]
Really, you are the expert here. I have never programmed in Turkish. But if I did which behaviour would I expect? The way it works now or your fix? I don't have any reservations towards your fix, I just want us to see it from both sides. :)

**Comment by ZioberMichal** [comment]
Hi @kbilsted,

a little sum up:

Q: Does app passes TT(Turkey Test) before PR?
A: Yes. It works because `equalsIgnoreCase` method is used whenever result of `toLowerCase/toUpperCase` methods is compared to something else. Notice that this `"setİsXxx".equalsIgnoreCase("setisxxx")` does `true`.

Q: Whether this pull request is needed?
A: Actually, not. But it shows that someone has checked source code, tested it, provided additional locale-profile, etc.

Q: Why I have added this: `toUpperCase(Locale.ENGLISH)`?
A: I did not want to change it. But I assumed that maybe in future new developer who will use `getMethodNameForField` method will not be remembering about TT and will use `equals` (instead of `equalsIgnoreCase`) method and this piece of code will fail under Turkish locales. This is just an prevention.

Actually, I am not expert in this area as well and this is only what I have noticed during testing this app. That's great that we are discussing about my changes because I do not want to push bigger bug ;) Let me know what do you think about it.

**Comment by kbilsted** [comment]
Thanks for the nice summary. I get the details now:)

Another question. How can we support Turkish programs using getters/setters?

**Comment by jamesbassett** [comment]
@ZioberMichal thanks for looking into this, and ditto on the nice summary. I remember updating to `equalsIgnoreCase` to fix another bug...I didn't realize it would fix this too :)

I don't think we should use `toUpperCase(Locale.ENGLISH)`. It will make the exception messages kind of weird (the setter/getter names will be in uppercase) and as you said it has no effect because we're ignore case when comparing method names.

I do agree that we should add the Turkey locale to the build to ensure the tests still pass. Are the extra turkey test methods needed, or do the current tests covert that? (if they are, then just fix the javadoc on your tests).

**Comment by kbilsted** [comment]
It seems we need to add a comment for equalsignorecase stating the two bugs that it fixes :) 

I don't mind the extra test as although the use case,now, may be covered by other tests that may not hold true in the future. And the test incur very little overhead.

**Comment by ZioberMichal** [comment]
@jamesbassett, @kbilsted thanks for all your comments. I did a little fix to my PR:
1. I have reverted my change in `ReflectionUtils#getMethodNameForField` method.
2. I also updated methods documentation.

Q: How can we support Turkish programs using getters/setters?
A: It's hard to say. In java programs in source code we can use UTF8 characters and every developer can name method using local characters. I hope that this `equalsIgnoreCase` method will take care about this but I am not sure that all cases are supported. If we want to be sure for 100% we have to make additional test class and try to create getters/setters with local characters and check whether everything is OK. 

Q: Are the extra turkey test methods needed, or do the current tests covert that?
A: I fixed documentation for added methods. I know that ''iPad" property covers the same problem but I think that extra one "isTurkish" does not bother a lot ;)

**Comment by kbilsted** [comment]
Hi @ZioberMichal  Many thanks for your input. Before a merge, I think we should combine the changesets since the net result is quite small. Combine eg. using  `git reset --soft head~4`

**Comment by kbilsted** [comment]
Already fixed by @jamesbassett  in an earlier commit. Closing and soon merging @ZioberMichal  PR documenting the details

**Comment by jamesbassett** [comment]
Looking at the linked article I don't we Super CSV actually passes the Turkey test (there's heaps of other issues apart from the 'i' one), but the specific issue reported is fixed, so maybe that's good enough?

**Comment by kbilsted** [comment]
Well, you are correct. We are back to my question regarding supporting turkish code - in a sense. How about we close this issue here and wait for someone having an actual problem to solve? If you disagree, feel free to reopen :+1:
