### ISSUE TITLE
CsvDozerBeanWriter partical write has problems

### ISSUE THREAD

**Issue by dota17** [super-csv/super-csv#177]
In this [file](https://github.com/super-csv/super-csv/blob/master/super-csv-dozer/src/test/java/org/supercsv/example/dozer/Writing.java) (https://github.com/super-csv/super-csv/blob/master/super-csv-dozer/src/test/java/org/supercsv/example/dozer/Writing.java), i think ```partialWriteWithCsvDozerBeanWriter()``` is not a example for partial writing. I have a problem when I am going to revise it.
```java
// ignore write answer/question 3
final String[] partialFieldMapping = new String[] { "age", "consentGiven", "answers[0].questionNo",
			"answers[0].answer", "answers[1].questionNo", "answers[1].answer", null, null };
beanWriter = new CsvDozerBeanWriter(new FileWriter("target/partialWriteWithCsvDozerBeanWriter.csv"),
				CsvPreference.STANDARD_PREFERENCE);
			
beanWriter.configureBeanMapping(SurveyResponse.class, partialFieldMapping);
```
This doesn't work. ```configureBeanMapping()``` method will throw an exception when patialFieldMapping has null.

I took a look at Reading example which can work normally

**Comment by dota17** [comment]
I will change the example of partial writing by using CsvDozerBeanWriter.

**Comment by kbilsted** [comment]
why close this issue?
