### ISSUE TITLE
Unit test is locale dependent

### ISSUE THREAD

**Issue by kbilsted** [super-csv/super-csv#18]
A test is locale dependent, and hence fail in Denmark

**Comment by jamesbassett** [comment]
Haha I probably would have just updated the test to use a different processor. I tweaked the test to avoid overriding the Locale (it's JVM wide, so a bit scary) and just the Locale support in the `FmtNumber` processor.

But more importantly, I've updated the build to allow building in a different (German) locale. It's driven by a Maven profile, so you can use it with `mvn clean verify -P germanLocale`. I've also updated the Travis build to build with both default and German locales to prevent this from happening again!
