### ISSUE TITLE
Super CSV Eclipse IDE

### ISSUE THREAD

**Issue by joaomartins-git** [super-csv/super-csv#181]
Hi all.

So, i'm having trouble "installing" the library in Eclipse IDE. Mostly becaus it has no JAR files (i think). 
Is there anyway to put it to work? or any explanation to why i'm having such difficulty?

Thanks all
Best Regards

**Comment by dota17** [comment]
**1.Using by super-csv source code**
Use the following command
```
git clone https://github.com/super-csv/super-csv.git
mvn package
```
jar files in /target for each subproject.(java version: 1.8, mvn version: 3.5)
**2.Using in Maven Project**
Please read: http://super-csv.github.io/super-csv/downloading.html

I'm glad to help you

**Comment by jjenkov** [comment]
I guess it depends on what you mean by "installing" the library. 

Do you need to use SuperCSV from inside your own application? Then you need the JAR file, or need to use Maven and a pom.xml file where you configure SuperCSV as a dependency inside.

Or do you need to clone SuperCSV and play around with the SuperCSV code itself inside Eclipse?

**Comment by joaomartins-git** [comment]
Hi!! 
Thanks for both of your replies, it helped a lot. 
Actually i was trying to include the libraries in my Ecplise project but without using Maven. That's why i had so many issues doing it.

Switched to a maven project, included the dependencies and it made wonders.
