### ISSUE TITLE
Grails Plug-in for super-csv

### ISSUE THREAD

**Issue by hansgru** [super-csv/super-csv#2]
Please add a Grails Plug-in for super-csv.

The only existing Grails CSV seems to use OpenCSV:

http://grails.org/plugin/csv
http://svn.codehaus.org/grails-plugins/grails-csv/trunk/

(another option might be to update the existing grails plug-in to use super-csv)

Thank you.

**Comment by kbilsted** [comment]
Hi Hans

Thanks for the suggestion. Since none of the team members have used Grails, changes are that this won't get done. Would you be interested in helping out with this yourself? We really could use more helping hands on the project.

cheers

**Comment by hansgru** [comment]
> Would you be interested in helping out with this yourself?

I will gladly help. I'm still a Grails newbie however.

> We really could use more helping hands on the project.

I inherited several projects that use OpenCSV (and Grails), that still need many fixings. I'm not acquainted with SuperCSV at the moment, but if I'll get more experience with it, sure :)

**Comment by kbilsted** [comment]
Sounds good. I'm closing this issue until you return work with more details as to how to integrate with grails.
