### ISSUE TITLE
While parsing files each line is unnecessarily copied

### ISSUE THREAD

**Issue by kbilsted** [super-csv/super-csv#20]
During tokenization the tokenizer copies each line to make parsing easier. This sports problems with long lines and/or embedded systems with low memory. A fix will reduce the maximum memory usage of the raw data by 50%.

**Comment by jamesbassett** [comment]
Looks good, just made some formatting updates.  I used the [merge method](http://blog.spreedly.com/2014/06/24/merge-pull-request-considered-harmful/#.VMxROIqUf0o) you mentioned using `hub` - I love it! Nice tidy commit history :)

I ran the benchmarking tests before/after and there was no difference - speed wise at least. I'd be interested in running it through a profiler (e.g. visualvm) to validate that it actually does use less memory, but agree that it should as we're halving the number of Strings created.

**Comment by kbilsted** [comment]
ok well, yeah that is nice, but im not sure if it was some other person who
did the PR, that he would then be added as a contributer in github. Think I
had to do an explicit merge in one of my other projects. Another annoyance,
is that I have to clean up some branching locally now :) I have a bugfix
branch sticking out..and another bugfix branch i never pushed i dont know
how to get rid of :) Happy git'in.. i better use the command prompt rather
than the gui.. the gui really suxx for Git compared to Hg ;)


regarding memory Ive just come to the conclusion that when using a buffered
file reader, we really dont know how many lines are cached..ie. how much
memory is being consumed.. this may be worse than the string copying for
embedded systems. Anyhow, I would not think you could register 50000 string
copies.. but maybe we need another data set. A sparse one with many int's
and decimals.. and many more rows.. maybe 200.000 ?  it will really guide
us when we do the encoding stuff



On Sat, Jan 31, 2015 at 5:28 AM, James Bassett <notifications@github.com>
wrote:

> Looks good, just made some formatting updates. I used the merge method
> <http://blog.spreedly.com/2014/06/24/merge-pull-request-considered-harmful/#.VMxROIqUf0o>
> you mentioned using hub - I love it! Nice tidy commit history :)
>
> I ran the benchmarking tests before/after and there was no difference -
> speed wise at least. I'd be interested in running it through a profiler
> (e.g. visualvm) to validate that it actually does use less memory, but
> agree that it should as we're halving the number of Strings created.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/super-csv/super-csv/issues/20#issuecomment-72304150>.
>



-- 
Med venlig hilsen
 -Kasper

**Comment by jamesbassett** [comment]
No the 'apply mail' method keeps the commit history (I was able to merge your pull request into my local master, update the formatting, and merge my commit into yours, then push back to GitHub with you still recorded as making the change). The same should go for anyone else who forks and creates a PR (they should still get credit).

Yeah I had to [git reset --hard upstream/master](http://stackoverflow.com/a/9646323/1068649) to get my fork in sync again.  I have 2 remotes (origin which points to my fork, and upstream which points to super-csv/super-csv). Seems to work well.

I'm not too fussed about optimisation, so happy to let you take the lead on that. What are your goals? I'd think that most dev's using the library only really care about how easy the API is to use, and how fast it is.  Can you explain why a file with ints/decimals is better? (isn't each line read in as a String anyway, so there's no difference??). I have the full CSV file used by the current benchmark (400k lines) if you're interested.

**Comment by kbilsted** [comment]
We will see a huge speed improvement when writing since we should not attempt to encode int/decimal/... this is now taking a major part of the time when writing. Thus with the file i've submitted, we should see significant improvements with you removing the call to `escape()`

**Comment by jamesbassett** [comment]
Actually if you look at the [commit](https://github.com/super-csv/super-csv/commit/1c336e286929d02b1d6c92753fc3a545f89f882d), the executed code is exactly the same :)  The `escape()` method was removed because the exact same functionality is now available via a preference - but the code from that method is still used in `writeRow()`.

**Comment by kbilsted** [comment]
Well, then we should make this a bit more intelligent. Before the code was too generalized and thus everything was escaped. I guess we need to do so in the case that all values must be enclosed in "" but for 'normal' writing of data, there is no need to attempt escaping certain types. I thought that was part of your change. But I can open an issue on this ample optimization opportunity.
