### ISSUE TITLE
String with backslash character

### ISSUE THREAD

**Issue by saul-mtz** [super-csv/super-csv#27]
Is writting a CSV Enconder the only way to put in the file strings like?
abc"def\ghi

**Comment by jamesbassett** [comment]
Sorry I'm not 100% sure what you're asking.  From the question title, it looks like #14, but the question body looks like you're asking if you can write a CSV file without any escaping. 

If so, then you should take a look at [SelectiveCsvEncoder](http://super-csv.github.io/super-csv/apidocs/org/supercsv/encoder/SelectiveCsvEncoder.html), which will disable escaping for some or all columns.

Just create your preferences like this:

    private static final CsvPreference NO_ESCAPING = 
        new CsvPreference.Builder(CsvPreference.STANDARD_PREFERENCE)
        .useEncoder(new SelectiveCsvEncoder().build();

**Comment by saul-mtz** [comment]
My problem was that I was using a [MySql LOAD DATA query](http://dev.mysql.com/doc/refman/5.1/en/load-data.html) to import the CSV data to a db but strings with backslashes was provoking some inconsistency.

I solved using the ESCAPED BY option.

Thanks for aswer and mantain your awesome tool.
