### ISSUE TITLE
CellProcessorAdaptor.validateInputNotNull should not be final

### ISSUE THREAD

**Issue by Rapster** [super-csv/super-csv#28]
Hi everybody,

First I'd like thank you all for this awesome library. Although, I have a request I'd like to custom the message thrown by some exception. Example in NotNull, instead of "this processor does not accept null input - if the column is optional then chain an Optional() processor before this one", I'd like to indicate the row, the column where occurs the exception. I was thinking to override this method of NotNull but I can't since it is "final".

I can't handle this in the catch statement, because I like sometimes how the message looks like, like in ParseBool although I'd like to add some information to this as well :)

If you have any other suggestions, please share :)

**Comment by jamesbassett** [comment]
Hi Rapster,

I think it'd be ok to remove the `final` in this case - I couldn't think of any reason anyone would want to override that method, but you've proved me wrong :)  @kbilsted what do you think?

Alternatively, you could override the `execute()` method instead to modify the message. For example, to append the row and column:

	@Override
	public Object execute(Object value, CsvContext context) {
		try {
			return super.execute(value, context);
		}
		catch(SuperCsvCellProcessorException e) {
			String originalMessage = e.getMessage();
			int rowNo = e.getCsvContext().getRowNumber();
			int colNo = e.getCsvContext().getColumnNumber();
			String message = String.format("%s, row=%d, column=%d", originalMessage, 
                        	rowNo, colNo);
			throw new SuperCsvCellProcessorException(message, e.getCsvContext(),
				e.getProcessor(), e.getCause());
		}
	}

**Comment by kbilsted** [comment]
I think the framework should support telling more exactly what went wrong out of the box.

*  So get rid of the final and 
* Change implementations on the information they provide when throwing

@Rapster  are you up for doing those changes and sending a pull request?

**Comment by Rapster** [comment]
Hi @kbilsted,

I would have been doing with pleasure but I can't, at least not now. How would you see this? Using properties file?

**Comment by kbilsted** [comment]
I think changing the behaviour for more informative error messages need not be configurable.
