### ISSUE TITLE
Multiple line breaks within a single quoted value causes StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by gmatadh** [super-csv/super-csv#30]
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658) ~[na:1.7.0_75]
	at org.supercsv.io.Tokenizer.readColumns(Tokenizer.java:155)
	at org.supercsv.io.AbstractCsvReader.readRow(AbstractCsvReader.java:179)
	at org.supercsv.io.CsvBeanReader.readIntoBean(CsvBeanReader.java:249)
	at org.supercsv.io.CsvBeanReader.read(CsvBeanReader.java:190)

I'm using v2.3.0

**Comment by kbilsted** [comment]
Thanks for reporting this

**Comment by jamesbassett** [comment]
This is a regression we introduced with 83ee9accc183054d5bd4f3d5184ea459ad4e1b5e (it works fine in 2.2.1).

Tokenizer now fails to parse consecutive newlines within quotes, e.g. 
```
"line1

line3"
```

**Comment by kbilsted** [comment]
Hi @gmatadh Bug fixed. Will be pushing soon. Are you able to pull, build and test your file before we do a release or if your file does not contain sensitive data, share it with us?

**Comment by gmatadh** [comment]
Looks good.  Thanks.

**Comment by kbilsted** [comment]
@james time for a release ? :)

**Comment by jamesbassett** [comment]
Ok, should be released now. Thanks again @gmatadh for picking this up :)
