### ISSUE TITLE
Misleading Exception with Mismatched Quotes

### ISSUE THREAD

**Issue by nickbabcock** [super-csv/super-csv#33]
Problem:

```
col1,col2
"foo","bar
"baz","zoo"
"aaa","bbb"
```

There is a human error on line two when the quote was left off the end. The exception that is thrown is misleading:

> org.supercsv.exception.SuperCsvException: unexpected end of file while reading quoted column beginning on line 4 and ending on line 4

I believe the error should read:

> org.supercsv.exception.SuperCsvException: unexpected end of line while reading quoted column on line 2

On a technical note, the reason why line 4 is chosen is because `quoteScopeStartingLine` keeps being reset when a new quote is found. 

The point would be better illustrated if there were a million lines between the quote and the end of the file because then it would be misleading for the debugger (a person) to track down the missing quote.

Since it is entirely valid for csv rows to span multiple lines, I believe the correct solution would be to add a configuration option (initially turned off to not break client code) that would make the tokenizer throw an exception if a newline is encountered and the mode is `QUOTESCOPE`. I realize that the comment [here][] mentions something about adding in a max lines functionality, which can be considered similar, but I don't think you can solve both of these problems with one configuration option (please correct me if I'm wrong...maybe if `maxLines==1`, it'd be a special case).

I know that I can derive my own `Tokenizer`, but believe the configuration option I'm suggesting is not terribly asinine and others may find it useful. If this idea is shot down, I guess I'll have to derive my own class.

Without further discussion, I'll open a pull request sometime tomorrow with the solution I have in my head, but I'd love for any possible kinks and input to be worked out now.

[here]: https://github.com/super-csv/super-csv/blob/91ca9b528edd7cfbca9e2aaefa9a14df41769dd0/super-csv/src/main/java/org/supercsv/io/Tokenizer.java#L131-L137

**Comment by jamesbassett** [comment]
Hi Nick,

Thanks for the detailed report - it's nice to see more than a 1-liner for a change :)

I think #4 would be an ideal solution - and it's as easy as adding a preference and adding an 'or multiline disabled' check to [this](https://github.com/super-csv/super-csv/blob/4cfa3b82b23a2422873aa6e538447aa974cd9857/super-csv/src/main/java/org/supercsv/io/Tokenizer.java#L118) line of `Tokenizer` to support single-line records only (it also has the benefit of being lenient about missing trailing quotes). 

There's a related issue #3 for the maxLines preference which conflicts a bit with this preference (as you said it's kind of the same thing if you set it to 1).

**Comment by nickbabcock** [comment]
Thanks for the support James, I'll make a pull request in probably less than an hour. I was able to wrap the combine maxLines functionality with disabling multi-line records in the style of #3 instead of #4. My reasoning is that while super-csv emphasizes leniency (which is a :+1: from me), the only benefit from being lenient as #4 describes is if the mistyped quote is in the last field.

The ideal case for disabling multi-line records

```
"foo","bar","baz
```

Here we know that the columns are `foo`, `bar`, `baz`, and that a trailing quote was left off the end. The tokenizer can continue without hesitation.  However, if the mistyped quote is anywhere else in the record, problems will occur anyways (if my understanding is correct)

```
"foo,"bar","baz"
```

This'll most likely cause an exception to be thrown anyways.

To me, mishandling quotes messes with the data, and so it is better to throw an exception early instead of continuing down the line and throwing an exception later -- which will most likely more cryptic. But as always I will defer to your opinions in the implementation.

**Comment by kbilsted** [comment]
I am away for a few days and can only look at this in half a week. Unsure if the renamed is descriptive enough

**Comment by kbilsted** [comment]
Forgotten to say great stuff and thanks for all your feed back so far @nickbabcock

**Comment by kbilsted** [comment]
@nickbabcock  @dmitry87  could issue #47  be of interest to you?
