### ISSUE TITLE
org.supercsv.cellprocessor.ParseDate is creating SimpleDateFormatter for every field it is parsing

### ISSUE THREAD

**Issue by VenkataRaju** [super-csv/super-csv#41]
Is it because it is not expensive to create(1*) or for thread safety purposes?
As format is not going to change, creating/compiling the format every time seems unnecessary (I think Guava synchronizes SDF in Gson in the similar case)

1* I see there is a compile() method in SimpleDateFormat similar to Pattern.compile()

**Comment by jamesbassett** [comment]
Yes it's purely for thread-safety purposes (which is one of the many reasons that I prefer Joda, and implemented the joda processors). While the readers/writers themselves aren't thread-safe, people tend to re-use processors in multiple threads, making this trade-off necessary.

**Comment by VenkataRaju** [comment]
Thank you for the clarification
