### ISSUE TITLE
Next line is skipped when there is a human error with skip character

### ISSUE THREAD

**Issue by dmitry87** [super-csv/super-csv#43]
Problem: #33
```
col1,col2
"foo","bar
"baz","zoo"
"aaa","bbb"
```
Expected
When we set maxLinesPerRow = 1. We read `"foo","bar` and get an error there.
Then read `"baz","zoo"` and `"aaa","bbb"` successfully.

Actual:
When we set maxLinesPerRow = 1. We read `"foo","bar` , read next line: `"baz","zoo"` and only then get the error.
Then read `"aaa","bbb"` successfully. In result we have one line skipped.

Message for skipping more then one line is invalid. When we set maxLinesPerRow = 2.
Both line currentLine and nextLine (eq. 2) should be in row, but now currentLine + maxLinesPerRow  = 4 (for example with `"foo","bar` above)

**Comment by kbilsted** [comment]
Why is this still open? is f7ae3ca357fc29cf821aff2e4e5c595fef4fccc4 to be merged? I guess we then need a new pull request for that one @dmitry87

**Comment by dmitry87** [comment]
@kbilsted I've just checked - both commits are in PR and were merged. The issue #43 Fixed. It should be closed
