### ISSUE TITLE
CsvMapWriter writes from Map<Object> 

### ISSUE THREAD

**Issue by poonammanning** [super-csv/super-csv#45]
Hello, I am using super-csv 2.3.1. I am trying to write Map<Object, Object> to csv. I tried to use CsvMapWriter but I get compilation error because CsvMapWriter.write method only accepts Map<String, ?> as the first argument whereas on the website on the link below, it is mentioned that CsvMapWriter "Writes each row of CSV from a- Map<String> or Map<Object> ". I do not see the implementation of Map<Object> in write method. 
http://super-csv.github.io/super-csv/writers.html

Can you please advise. I don't think I am missing anything. All the examples so far I have seen are only passing Map<String> . 

If I cannot pass Map<Object>, do I need to create a custom cell processor? 

Thanks .

**Comment by poonammanning** [comment]
This is my first use of github.  I have just realized that my post isn't posted correctly. Somehow the generics are missing with the class names so I am having to put it in quotes :( . I am rewriting my query here - 

Hello, I am using super-csv 2.3.1. I am trying to write Map"<"Object, Object">" to csv. I tried to use CsvMapWriter but I get compilation error because CsvMapWriter.write method only accepts Map"<"String, ?">" as the first argument whereas on the website on the link below, it is mentioned that CsvMapWriter "Writes each row of CSV from a- Map"<"String">" or Map"<"Object">" ". I do not see the implementation of Map"<"Object">" in write method. 
http://super-csv.github.io/super-csv/writers.html


Can you please advise. I don't think I am missing anything. All the examples so far I have seen are only passing Map"<"String">" . 

If I cannot pass Map"<"Object">" to the write method, do I need to create a custom cell processor? 


Thanks .

**Comment by kbilsted** [comment]
It seems many cannot find the examples in the left menu. You are not the first to get lost. Have a look at this page and please respond if it solves your problem

http://super-csv.github.io/super-csv/examples_writing.html

**Comment by poonammanning** [comment]
I have seen this example and I am using ICsvMapWriter example , except that the map I want to write to Csv has key of type Object whereas in the example , map's key is String type . The write method doesn't accept Map with key as Object type .

Thanks ,
Poonam

Sent from my iPhone

On 14 May 2015, at 19:44, Kasper B. Graversen <notifications@github.com<mailto:notifications@github.com>> wrote:


It seems many cannot find the examples in the left menu. You are not the first to get lost. Have a look at this page and please respond if it solves your problem

http://super-csv.github.io/super-csv/examples_writing.html

-
Reply to this email directly or view it on GitHub<https://github.com/super-csv/super-csv/issues/45#issuecomment-102132405>.

The information contained in this email and any attached files is confidential and intended solely for the addressee(s). The email may be legally privileged or prohibited from disclosure and unauthorised use. If you are not the named addressee you may not use, copy, or disclose this information to any other person. If you received this message in error please notify the sender immediately and delete it from your system.



Any opinion or views contained in this email message are those of the sender, and do not represent those of the Company in any way and reliance should not be placed upon its contents. Unless otherwise stated, this email message is not intended to be contractually binding. Where an Agreement exists between our respective companies and there is conflict between the contents of this email message and the Agreement then the terms of that Agreement shall prevail.




Excelian Limited / 44 Featherstone Street London / EC1Y 8RN / United Kingdom


T +44 (0)207 336 9595 / www.excelian.com

**Comment by kbilsted** [comment]
Ah I see your point. Not sure of a generic way to turn objects intro sane strings for the header. Any ideas? Maybe we need tune the docs slightly :)

**Comment by jamesbassett** [comment]
I would just create a new map with the keys converted to Strings. The API relies on the String values in the `nameMapping` array to match with keys in the Map - so even if you allowed Object keys and `toString()`'d them, the values in that array would be horrendous.
