### ISSUE TITLE
CsvDozerBeanWriter using quote mode and deep mapping

### ISSUE THREAD

**Issue by vrechdelaval** [super-csv/super-csv#48]
First, thanks for this great and useful library.

I am using super-csv 2.1.0 and I am trying to write files with CsvDozerBeanWriter.
I am using a custom CsvPreference to use quote mode but it doesn't work with a bean with deep mapping while it works with a bean without deep mapping.
It writes file with good data but without wanted quotes. Here is my code:

```
// create custom CsvPreference ('columnsToQuote' is an array of booleans)
CsvPreference myPref = new CsvPreference.Builder(CsvPreference.TAB_PREFERENCE).
		useQuoteMode(new ColumnQuoteMode(columnsToQuote)).
		skipComments(new CommentStartsWith("//")).build());

// create and configure writer
ICsvDozerBeanWriter beanWriter = new CsvDozerBeanWriter(
		new FileWriter(new File(directory, fileName)),
		myPref);

// configure the mapping from the fields to the CSV columns ('fieldMapping' is the array of Strings)
beanWriter.configureBeanMapping(MyBean.class, fieldMapping);

// write header ('headers' is an array of Strings)
beanWriter.writeHeader(headers);

// write bean ('bean' is an MyBean and 'processors' is an array of CellProcessor)
writer.write(bean, processors);
```

It seems to me that there is a bug when using quote mode with deep mapping.

I hope I have been clear. Please let me know what you think.

**Comment by jamesbassett** [comment]
Hi, is it possible to see a full example? It would really help to see the definitions of `MyBean` and `fieldMapping`, and most importantly the CSV output, so we can see what the bug actually is.

**Comment by vrechdelaval** [comment]
Solution found by simplifying my code to give you a complete example: my unit test checked surrounding double quotes while logically removed because I read the file with CsvPreference.TAB_PREFERENCE.

I'm really sorry I opened this issue for nothing.

**Comment by jamesbassett** [comment]
No worries :)

**Comment by kbilsted** [comment]
:+1:
