### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by kbilsted** [super-csv/super-csv#64]
Hi team, is it time to soon do a release? I guess we need to update the version log with all the stuff. Currently 44 commits have been made since last release.

**Comment by ZioberMichal** [comment]
Good idea. Current version is stable and new test suite should prove that everything works properly.

**Comment by ds-perfit** [comment]
Any ideas when the new release will be available? I'd like to use the multi line limit.
Thanks!

**Comment by jamesbassett** [comment]
Ok @kbilsted I've updated the release notes and done a minor tidy up. I'm now officially handing the reins back to you (that will probably be my last commit!). It's been great fun and I've learnt heaps running this project, but it's time for me to move on and pursue other things.

Hopefully the [guide to releasing](https://github.com/super-csv/super-csv/wiki/Performing-a-release) is thorough enough - if you have any issues let me know.

James out :)

**Comment by kbilsted** [comment]
@ZioberMichal @singularityfx  are any of you interested in gathering the changes since the last commit and following james' guide?

**Comment by ZioberMichal** [comment]
Hi @kbilsted, I am on vacation until 1st of October... I am not sure whether I will be able to do this before this date..

**Comment by singularityfx** [comment]
@kbilsted @ZioberMichal I would like to finish issue #65 first. Then I can look into it.

**Comment by singularityfx** [comment]
@kbilsted @ZioberMichal Guide mentions use of PGP. In Russia we have legislative limitations on use of cryptographic software. I would prefer not to touch it without clear understanding of these limitations. Sorry guys....

**Comment by jamesbassett** [comment]
Haha wow. It's only used to generate the `.asc` signatures of the files uploaded to maven central (a maven central requirement), similar to an MD5 hash but with the added security of the public key being distributed on many key servers. @kbilsted you might have to do it. I can do it as a last resort, but was hoping you guys could figure it out without me :)

**Comment by ZioberMichal** [comment]
@kbilsted what is the status of the releasing? Are we waiting for the task #68?

**Comment by kbilsted** [comment]
I have not touched it. I was hoping one of you guys could be persuaded into doing the release. :-)

Personally, I'm not really waiting for the completion of a specific feature. I think there are more than enough features to warrant a release.

**Comment by ZioberMichal** [comment]
I understand. Task #68 we can push in next release. 

I will try to push release this week.

**Comment by kbilsted** [comment]
There is a "assignee" in the right-hand menu

**Comment by ncapponi** [comment]
As the release have not been done yet, is there any chance that the PR I submitted (#73) is included in the release ?

**Comment by ZioberMichal** [comment]
I want to release it finally this week (tomorrow or day after tomorrow). @kbilsted I can wait for this PR if you need some time to check it.

**Comment by pietroaragona** [comment]
Hi all,
I'm reading @jamesbassett 's [guide](https://github.com/super-csv/super-csv/wiki/Performing-a-release) in order to help you for next releases.
I created JIRA account but  I don't understand what to do with [Super CSV ticket](https://issues.sonatype.org/browse/OSSRH-2458). Maybe I need to do any action on it, like watch it or simply I need the account on JIRA? 
Thanks, Pietro

**Comment by jamesbassett** [comment]
I believe you need to comment on the ticket to ask for your jira username
to be given permission to the super CSV repo

**Comment by ncapponi** [comment]
Hi @ZioberMichal, do you have any plan to do the release soon ? Just asking, no pressure ;-)

**Comment by ZioberMichal** [comment]
I want to do it this week. I was waiting for your PR and since it was merged I will release new version as soon it possible.

**Comment by ZioberMichal** [comment]
Hi @kbilsted I have updated release notes and now they should contains all significant changes. If you think that we have all of them, please merge this PR and I will try to generate new version then.
Let me know what do you think.

**Comment by kbilsted** [comment]
I have fallen ill.flu. hope to be back within a week. Ask singularfx for a
review . I think you have rights to merge the or now.let me know
Den 20/10/2015 00.39 skrev "Michał Ziober" <notifications@github.com>:

**Comment by singularityfx** [comment]
@kbilsted @ZioberMichal I've checked commits history and can confirm that release notes #76  contain all significant changes since 2.3.1

**Comment by ZioberMichal** [comment]
@singularityfx , thanks for review. 
@kbilsted, yes, I see "Merge pull request" button. If you want I can merge it.

**Comment by kbilsted** [comment]
Sure
I think you need a key to release on maven
Den 21/10/2015 11.07 skrev "Michał Ziober" <notifications@github.com>:

**Comment by jamesbassett** [comment]
Yeah I recommend creating your OSS nexus account and commenting on the jira ticket to get access to publish to maven asap as it might take a day or so.

And also to generate your pgp key pair and distribute it.

Both steps should be documented on the release wiki page. I'm flying back from Japan tomorrow but can help out whenever I get an internet connection. But it'd be awesome for you to figure it out for yourself (like I had to!)

**Comment by ZioberMichal** [comment]
I have merged it (it was my first PR merge ever)

@jamesbassett, I created OSS Nexus account one week ago and I have generated pgp key already. Today evening I will try to release new version. I think that all prerequisites were done.

**Comment by ZioberMichal** [comment]
Hi guys, I wanted to release new version today but I had some problems with GPG2 tool which were unexpected to me. At the end I was able to invoke `mvn release:prepare` command successfully but I pushed new changes to new branch `super-csv/master` accidentally ... :wink:. Sorry for that. I will remove it tomorrow and I will try to release new version on master branch. 

I have never deleted branches on Github before and I afraid that I can do something wrong: Does this command will be OK: `git push origin :super-csv/master`?

**Comment by jamesbassett** [comment]
Hey, just on the shinkansen to the airport! As well as deleting that new branch you'll have to remove the new tag as well (it will get recreated when you prepare the release again).

Not sure how you created the new branch, but just remember that you won't have to execute any git commands, maven will do it all for you.

And don't worry about making mistakes, it's the only way to learn!

**Comment by kbilsted** [comment]
Yes its the only way to learn, but please don't delete all the code and
push :) have a nice trip James.
Den 22/10/2015 06.04 skrev "James Bassett" <notifications@github.com>:

**Comment by ZioberMichal** [comment]
Haha. Don't worry. I will delete this branch and tag and I will run the process again.

**Comment by laurentvaills** [comment]
Hi everyone,

I just wanted to know if @ZioberMichal had some chance to make some progress while running the release process again.
We have some pending works on the ForgeRock products waiting for that release (and more specifically the performance bugfix related to the writer.)

Regards.

**Comment by ZioberMichal** [comment]
Hi @laurentvaillsm, yes I will do it tomorrow. 
Sorry that it takes so long but I have a lot of work and I am so exhausted at the evening that I am not able to do anything more on github...

**Comment by laurentvaills** [comment]
ok, thanks for your answer. 
I understand well that you're doing this on your free time.

**Comment by kbilsted** [comment]
If  you are pressed for time do a fork and a local release. Our release
should hold the same content and you can switch over easily. :-)
Den 27/10/2015 17.21 skrev "Laurent Vaills" <notifications@github.com>:

**Comment by ZioberMichal** [comment]
Hi guys, I want to inform you that new version has been released! I hope that soon it will appear on Maven repository.

@kbilsted, could you please check whether everything was done properly?

**Comment by jamesbassett** [comment]
Great job @ZioberMichal :) 

Looks good to me!
* Available via maven central - check
* Website is updated - check
* Distribution attached to tag on Github with link to release notes - check

The only outstanding things are:
* close 2.4.0 milestone on Github (and create a new one for the next release)
* add distribution zip file to SourceForge (I'll let you guys decide whether you want to keep doing this, or call it quits on SourceForge....maybe it's time to just let it die haha....so many people still download from here....why????)

I'm going to remove myself from the super-csv organization now - I just wanted to make sure this release went smoothly before leaving.

Once again, thanks everyone for all the fun over the years. I've learnt so much from this project, but it's time to move on and give others the opportunity now. I'm always contactable in case you have any questions (like "why the hell did you do that??" :P)

Cheers,
James

**Comment by ZioberMichal** [comment]
Hi @jamesbassett, thanks for checking new release.

@kbilsted, could you create new milestone. I think that we can skip SourceForge. People should understand that now we are using GitHub ;)

@jamesbassett thank you for all your help you gave me and I wish you all the best and only "good" projects. :smiley:

**Comment by ncapponi** [comment]
Thanks for the release @ZioberMichal !

**Comment by laurentvaills** [comment]
Many thanks @ZioberMichal .

**Comment by kbilsted** [comment]
Great job :)
