### ISSUE TITLE
Unique Cell Processor Not throwing Exception

### ISSUE THREAD

**Issue by phovsepian-seven10** [super-csv/super-csv#70]
To my understanding, I've been using Super CSV for a few hours, the Unique constraint as noted in the javadocs as being a constraint that "ensures that all rows in a column are unique". Following the examples online I created the following CellProcessor function:

```java
    private static CellProcessor[] getProcessors() 
	{    
		final CellProcessor[] processors = new CellProcessor[] 
		{				        
	        new NotNull(new ParseEnum(FileResultStatus.class)), // status
	        new NotNull(new LMinMax(0L, LMinMax.MAX_LONG)), 	// file size
	        //new NotNull(new FmtDate("")),						// timestamp
	        new NotNull(new LMinMax(0L, LMinMax.MAX_LONG)), 	// duration
	        new Unique() 				// file name/path
        };
        
        return processors;
	}
```

While running a test, I noticed that the Unique constraint was not generating an exception when it should. I even make two consecutive calls to write with the same map object and do not see an exception generated.

```java
    public void writeResults(FileResultWork resultWork) throws IOException
	{
		// create the customer Maps (using the header elements for the column keys)
        final Map<String, Object> csvResultMap = new HashMap<>();
        csvResultMap.put(CSV_JOB_RESULT_HEADERS[0], resultWork.getFileResult());
        csvResultMap.put(CSV_JOB_RESULT_HEADERS[1], resultWork.getFileSize());
        csvResultMap.put(CSV_JOB_RESULT_HEADERS[2], resultWork.getDuration());
        csvResultMap.put(CSV_JOB_RESULT_HEADERS[3], resultWork.getFileName());
        
        mapWriter.write(csvResultMap, CSV_JOB_RESULT_HEADERS, getProcessors());
        mapWriter.write(csvResultMap, CSV_JOB_RESULT_HEADERS, getProcessors());
	}
````

I also tried to make that cell processor a UniqueHashCode but to no avail. That particular field is very simply a String, if that makes a difference. Using Java 8 and the latest maven build from your web site. Insight  would be appreciated - thanks.

**Comment by jamesbassett** [comment]
Try

        CellProcessor[] processors = getProcessors();
        mapWriter.write(csvResultMap, CSV_JOB_RESULT_HEADERS, processors);
        mapWriter.write(csvResultMap, CSV_JOB_RESULT_HEADERS, processors);

The `Unique` cell processor has state - you need the same instance to process all rows for it to work.

**Comment by phovsepian-seven10** [comment]
Ah - that solved the problem. I haven't looked at the internals but can understand why this would. It does make abstraction a bit trickier but nonetheless, works. I appreciate the quick response.
