### ISSUE TITLE
Improve write performance in multi-threaded environment

### ISSUE THREAD

**Issue by ncapponi** [super-csv/super-csv#71]
When writing a CSV file in a multi-threaded environment (multiple threads are writing to a CSV file), I noticed that there is contention in the AbstractCsvWriter class.

As the write operation is synchronized, it is better to reduce the number of calls in  a multi-threaded scenario.

I've performed some test using JMH, showing that we can improve performance with two changes in the AbstractCsvWriter class:
- using the provided Writer instead of wrapping it into a BufferedWriter
- calling write only once in writeRow() method, using a StringBuilder to build the complete row

Moreover the last change ensure a row is not chunked when writing to a file.

- Result for SuperCSV 2.3.1 with 1 thread: 1046955.864 ±(99.9%) 41455.729 ops/s [Average]
- Result for SuperCSV 2.3.1 with 5 threads: 2851550.689 ±(99.9%) 232962.406 ops/s [Average]
- Result for SuperCSV 2.3.1 "optimized" with 1 thread: 1243468.805 ±(99.9%) 28794.351 ops/s 
- Result for SuperCSV 2.3.1 "optimized" with 5 threads: 3889083.630 ±(99.9%) 129756.818 ops/s [Average]
 
I can provide the code for the benchmark if needed.

I will submit a PR if you agree for this change.

**Comment by laurentvaills** [comment]
Hi, 

I am a co-worker of Nicolas, and we studied together on that issue.

Regarding the synchronized write operation, here is more details : 
As you can see in the [Writer](http://hg.openjdk.java.net/jdk7/jdk7/jdk/file/9b8c96f96a0f/src/share/classes/java/io/Writer.java) class, every write operation ends up into a synchronized block. So if we write : 

```java
Writer writer = ... ;
writer.write(QUOTE_CHAR);
writer.write(content);
writer.write(QUOTE_CHAR);
writer.write(SEPARATOR);
```

The code above indeed creates 4 synchronized blocks, which has a cost in term of performance, even in a single threaded application.
So refactoring the above code to something like this : 

```java
Writer writer = ... ;
StringBuilder builder = new StringBuilder();
builder.append(QUOTE_CHAR);
builder.append(content);
builder.append(QUOTE_CHAR);
builder.append(SEPARATOR_CHAR);
writer.write(builder.toString());
```

We now create only 1 synchronized block, which is more efficient.

Furthermore, as a bonus thanks to that intrinsic lock in the class Writer, then the write operation is atomic and so we can share the same CsvWriter between threads. This does not make supercsv completely thread-safe but that may be a step towards this.

The other proposal regarding the `BufferedWriter` : currently supercsv wraps every writer with a `BufferedWriter`. But there may be some cases that the writer passed in parameters is already buffered : either it was already wrapped with a `BufferedWriter` or it can be a custom implementation of `Writer` that already handles its own buffering or simply does not support buffering at all. 
So what we propose may be to stop wrapping the parameter writer with a `BufferedWriter` . Another less aggressive proposal can be to add another constructor with a boolean parameter named `buffered` so the developer can decide wether or not the `writer` can be wrapped by a `BufferedWriter` or not.

**Comment by kbilsted** [comment]
Great with the analysis! Am I reading this correctly, that for single threaded the performance is 50% slower? Perhaps we need a completely separate implementation for multithreaded stuff since it seems odd to penalize all other users.

I agree that the API is somewhat old fashioned, in that it doesn't support "constructor injection" of the Writer. Which in this modern day'n age is for granted. Rather than a boolean I think it would be much better to be able to privide a Writer which then is not wrapped by SuperCsv. that way you are free to do whatever you wish.

**Comment by ncapponi** [comment]
I've submitted a new version of the PR (https://github.com/super-csv/super-csv/pull/73). 
I've introduced a new constructor because @ZioberMichal noted that it would break backward compatibility otherwise. Do you suggest another approach ?

Regarding performance, it is not slower in the single threaded case (the lines from JMH indicates "N plus/minus V" where N is the number of ops and V the variance due to multiple tests) 
* Result for SuperCSV 2.3.1 with 1 thread: 1,046,955
* Result for SuperCSV 2.3.1 "optimized" with 1 thread: 1,243,468
By grouping all writes for a single row into a single one, this is more efficient.

**Comment by ncapponi** [comment]
I've created a gist for the JMH performance test: https://gist.github.com/ncapponi/a89674837e4d57af3ed7

**Comment by ncapponi** [comment]
I've run the existing StandardCsvWritingBenchmarkTest with different implementations to have more insight on performances:
* Current implementation (before PR)
  * StandardCsvWritingBenchmarkTest.testCsvMapWriter: [measured 10 out of 15 rounds, threads: 1 (sequential)] round: **0.20** [+- 0.03], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 6, GC.time: 0.01, time.total: 2.88, time.warmup: 0.84, time.bench: 2.04
* Current implementation + removing BufferedWriter wrapping
   * StandardCsvWritingBenchmarkTest.testCsvMapWriter: [measured 10 out of 15 rounds, threads: 1 (sequential)]
 round: **0.23** [+- 0.03], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 4, GC.time: 0.01, time.total: 3.56, time.warmup: 1.23, time.bench: 2.33

Now using the StringBuilder
* With BufferedWriter wrapping
  * StandardCsvWritingBenchmarkTest.testCsvMapWriter: [measured 10 out of 15 rounds, threads: 1 (sequential)]
 round: **0.15** [+- 0.02], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 4, GC.time: 0.01, time.total: 2.38, time.warmup: 0.89, time.bench: 1.49
* Without BufferedWriter wrapping
  * StandardCsvWritingBenchmarkTest.testCsvMapWriter: [measured 10 out of 15 rounds, threads: 1 (sequential)]
 round: **0.15** [+- 0.03], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 3, GC.time: 0.00, time.total: 2.25, time.warmup: 0.72, time.bench: 1.53

As you can see the use of StringBuilder really improve things. Then using or not the BufferedWriter has no obvious impact, at least for the implemented test.
