### ISSUE TITLE
Issues with Trim and Truncate

### ISSUE THREAD

**Issue by nagraj321** [super-csv/super-csv#83]
I'm facing a problem while triming and truncating the values using super csv. 
Sample text: TC_VS 04\tUpdate Payment Term on existing Contract - Standard Master Agreement - Subagreement:TC_VS 06\ntest..\ntest.

I need to remove all the spaces and if the text is greater then the specified length then i need to truncate it. But is it not trimming it. 

Out put:

**Line No 1** "TC_VS 04	Update Payment Term on existing Contract - Standard Master Agreement - Subagreement:TC_VS 06
**Line No2** test..
**Line No3** test."	Effe	Joshua Bloch	Addision-Wesley	05/08/2008	38.0	

Below is the sample code.

import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

import org.supercsv.cellprocessor.FmtDate;
import org.supercsv.cellprocessor.Optional;
import org.supercsv.cellprocessor.ParseDouble;
import org.supercsv.cellprocessor.Trim;
import org.supercsv.cellprocessor.Truncate;
import org.supercsv.cellprocessor.constraint.NotNull;
import org.supercsv.cellprocessor.ift.CellProcessor;
import org.supercsv.io.CsvBeanWriter;
import org.supercsv.io.ICsvBeanWriter;
import org.supercsv.prefs.CsvPreference;

public class Test {

	static void writeCSVFile(String csvFileName, List<Book> listBooks) {
		System.out.println(new Date());
		ICsvBeanWriter beanWriter = null;
		CellProcessor[] processors = new CellProcessor[] { new NotNull(new Truncate(250, new Trim())), // ISBN
				new Optional(new Truncate(4)), // title
				new NotNull(), // author
				new NotNull(), // publisher
				new FmtDate("MM/dd/yyyy"), // published date
				new ParseDouble(), // price
				new NotNull()
		};
	
		try {
			beanWriter = new CsvBeanWriter(new FileWriter(csvFileName), CsvPreference.TAB_PREFERENCE);
			
			final String[] fieldMapping = new String[] { "isbn", "title", "author", "publisher", "published", "price", "co_author"};
			
			for (Book aBook : listBooks) {
				try{
				beanWriter.write(aBook, fieldMapping, processors);
				} catch (Exception e) {
					System.err.println("ERROR" + e);
				}
			}
			System.out.println("Success");

		} catch (IOException ex) {
			System.err.println("Error writing the CSV file: " + ex);
		} finally {
			if (beanWriter != null) {
				try {
					beanWriter.close();
				} catch (IOException ex) {
					System.err.println("Error closing the writer: " + ex);
				}
			}
		}
	}

	public static void main(String[] args) throws ParseException {
		// creates some dummy data
		DateFormat dateFormater = new SimpleDateFormat("MM/dd/yyyy");

		Book book1 = new Book("TC_VS 04\tUpdate Payment Term on existing Contract - Standard Master Agreement - Subagreement:TC_VS 06\ntest..\ntest.", "Effective Java", "Joshua Bloch", "Addision-Wesley",
				dateFormater.parse("05/08/2008"), 38.00, "");

		List<Book> listBooks = Arrays.asList(book1);

		String csvFileName = "Java_Books.csv";
		writeCSVFile(csvFileName, listBooks);
	}

}

import java.util.Date;

public class Book {

	private String isbn;
	private String title;
	private String author;
	private String publisher;
	private Date published;
	private double price;
	
	private String co_author;

	public Book() {
		// this empty constructor is required
	}

	public Book(String isbn, String title, String author, String publisher, Date published, double price,String co_author) {
		this.isbn = isbn;
		this.title = title;
		this.author = author;
		this.publisher = publisher;
		this.published = published;
		this.price = price;
		this.co_author = co_author;
	}

	public String getIsbn() {
		return isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getPublisher() {
		return publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	public Date getPublished() {
		return published;
	}

	public void setPublished(Date published) {
		this.published = published;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public String getCo_author() {
		return co_author;
	}

	public void setCo_author(String co_author) {
		this.co_author = co_author;
	}
	
	

}

**Comment by kbilsted** [comment]
Why  did you close the ticket
