### ISSUE TITLE
Java 8 Language level ICsvBeanReader method invocation

### ISSUE THREAD

**Issue by inglor** [super-csv/super-csv#86]
With JDK 8 I get an IDE error when using the `ICsvBeanReader.read(Class<T>, String[], CellProcessor[])` method. This is probably caused from the new JLS chapter about Invocation Applicability Inference [1].

If I switch to JDK 7 there's no error. This is observable even if I just change the source and target language level to 7.

The image shows the error
![jls8](https://cloud.githubusercontent.com/assets/301857/11547563/d20d1d5e-994c-11e5-9cb5-3df5fbd4d688.png)

And here's a small maven project:
https://dl.dropboxusercontent.com/u/7969252/super-csv-test.7z

[1]: https://docs.oracle.com/javase/specs/jls/se8/html/jls-18.html#jls-18.5.1

**Comment by inglor** [comment]
This syntax works fine in both 7 and 8

`while((customer = beanReader.<CustomerBean>read(CustomerBean.class, header, processors)) != null) {`

**Comment by kbilsted** [comment]
Hi @inglor 

Great finding! Are you able to send a pull request ?

**Comment by inglor** [comment]
I'm not sure if the source code needs some change to be honest. After reading through some various SO posts [1], [2] related to that it's the way that you call the method which needs to change as I indicated above.

I'd surely change the example but that's it I think.

[1]: http://stackoverflow.com/questions/32294140/java-8-reference-to-method-is-ambiguous?lq=1
[2]: http://stackoverflow.com/questions/28466925/java-type-inference-reference-is-ambiguous-in-java-8-but-not-java-7?lq=1

**Comment by ZioberMichal** [comment]
Good to know, I will take a look on this next week.

**Comment by ZioberMichal** [comment]
In cases like this user should explicitly tell to Java compiler in version 7 and 8 "hey I need this type" using this syntax: `reader.<TypeName>read(...)`. Actually, we do not have to reimplement this method signature. I think we can close this issue.
