### ISSUE TITLE
Delete File

### ISSUE THREAD

**Issue by nagraj321** [super-csv/super-csv#87]
Just want to know whether we can delete a file using supercsv.

1. First created the ICsvBeanWriter
2. Write the data using ICsvBeanWriter
3. Close the ICsvBeanWriter

even if the data is not available in the step 2 we are creating the file and their is not way to delete the file.

any idea how can we achieve this?

Thanks,
Nagaraju

**Comment by kbilsted** [comment]
HI i'm not fully sure i understand the problem. Try submitting some Java code for how you think you could use the framework. Why not simply delete the file yourself? why start wrtiting to a file before you check if you have data to write?

**Comment by ZioberMichal** [comment]
`ICsvBeanWriter` is just an abstraction for writing any bean as CSV row. `CsvBeanWriter` class pushes CSV `String` to `Writer` object which is given in constructor. You probably uses [FileWriter](https://docs.oracle.com/javase/7/docs/api/java/io/FileWriter.html) class which creates file at the beginning. 
You have two solutions:
1. You can use [StringWriter](https://docs.oracle.com/javase/7/docs/api/java/io/StringWriter.html) which writes data to memory. At the end, after writing, you can check the length of the String and save it to file if needed. Consumes time and memory but doesn't create file if it is not needed.
2. You can close the stream and remove file if it is empty.

Summary: does not look like an issue in super-csv library. I vote to close this.

**Comment by kbilsted** [comment]
+1 @ZioberMichal
