### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [super-csv/super-csv#89]
Hi
The following source files are without license headers:
super-csv-2.4.0/super-csv-java8/src/main/java/org/supercsv/cellprocessor/time/AbstractTemporalAccessorFormattingProcessor.java
super-csv-2.4.0/super-csv-java8/src/main/java/org/supercsv/cellprocessor/time/AbstractTemporalAccessorParsingProcessor.java
super-csv-2.4.0/super-csv-joda/src/main/java/org/supercsv/cellprocessor/joda/AbstractJodaFormattingProcessor.java
super-csv-2.4.0/super-csv-joda/src/main/java/org/supercsv/cellprocessor/joda/AbstractJodaParsingProcessor.java

Please, add license headers.
The Fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification
Thanks in advance

**Comment by ZioberMichal** [comment]
Hi @puntogil,
    thanks for showing this bug. We will add licence to these files.

**Comment by fseifert** [comment]
I have put a PR for this topic.
I have just used the license header used in nearly all code files. Since all those changed files initially had no license header, it think its just ok to use the "standard" header.
