### ISSUE TITLE
Add support for non-public beans

### ISSUE THREAD

**Issue by fseifert** [super-csv/super-csv#92]
Currently only beans with access level "public" can be used in CsvBeanReader.
Looking at CsvBeanReader class shows clazz.getInstance() for the constructor and method.invoke() for the setter.
I have just tested replacing this with the code in the attachment, basically its finding the default constructor by reflection and invoking both constructor and method with ensuring access by calling c.setAccessible(true);
At a first glance, all tests still succeed with that change-
You think that would be something useable? If so, I can implement it and provide test cases for it along.

[privateAccess.txt](https://github.com/super-csv/super-csv/files/145298/privateAccess.txt)

**Comment by ZioberMichal** [comment]
Hi @fseifert,
    your changes should not break anything but mainly `CsvBeanReader` works with `POJO` classes which by default should have public default constructor and public getter/setter methods. In my opinion client-developer should understand that these classes which he wants to read in CSV should be "valid".
I am interesting how `Hibernate` or `Jackson` libraries treats situations like this. If they "magically" changes access level in runtime we could do the same but if not, I think, we can leave it as it is.

@kbilsted, what do you think?

Anyway, thanks for raising this discussion.

**Comment by fseifert** [comment]
Hi @ZioberMichal,
According to [http://www.javalobby.org/java/forums/m91937279.html#](url) and here [https://hibernate.atlassian.net/browse/HV-331](url) and here [https://github.com/hibernate/hibernate-orm/blob/1e44e7420b7af10adc9547a461f02a6d979624f1/hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessEnhancedImpl.java](url) at least Hibernate seems to use that feature.

The background for this feature is, that I'm working on a library which only publish interfaces and a factory and one of the factory method just takes in a file path and returns a list of domain specific pojos.
Both the csv and the interfaces are already defined but don't match the super-csv requirements.

**Comment by ZioberMichal** [comment]
Thanks for additional explanation! :+1: 

In this case I think it would be a valuable patch. Try to create new PR and with these changes.

**Comment by kbilsted** [comment]
Looks nice, is it ok for you to fix the simple formatting and equals issues ?

**Comment by kbilsted** [comment]
fixed by PR
