### ISSUE TITLE
[Java8] ICsvBeanWriter could receive a collection of function references instead of names

### ISSUE THREAD

**Issue by longtimeago** [super-csv/super-csv#93]
This should make it ICsvBeanWriter fail in compile time if bean field name was changed due to refactoring.

Now it fails in runtime :( too late

**Comment by ZioberMichal** [comment]
:+1: 

It wold be a valuable patch.

**Comment by longtimeago** [comment]
@ZioberMichal Here is the PR https://github.com/super-csv/super-csv/pull/97

**Comment by ZioberMichal** [comment]
Idea was implemented and merged to trunk.
