### ISSUE TITLE
Encoding UTF-16LE not recognized

### ISSUE THREAD

**Issue by arnaud-web** [super-csv/super-csv#96]
I am triying to write a file with UTF-16LE encoding.

Here is my code : 
`
private CsvPreference csvPreference;
`
....
`
String charsetValue = "UTF-16LE";
`
`
ICsvListWriter listWriter = new CsvListWriter(new OutputStreamWriter(new FileOutputStream(new File(path)), Charset.forName(charsetValue)), csvPreference);
`
When I open the output file with Notepad ++, the encoding is not detected as UTF-16LE.
When I modify the charsetValue to "UTF-16", the encoding of output file is UTF-16BE

Can you help me ?

**Comment by ZioberMichal** [comment]
Hi @arnaud-web, do you still have a problem with encoding? I am not sure what documentation for your version of Notepad++ says but maybe this is just how it works? Have you tried read written data and check whether everything is OK? Please, let me know what is the status of this problem.

**Comment by kbilsted** [comment]
@arnaud-web  Im not sure we try to do clever stuff with the encodings. what happens if you save a simple textfile using 

    String charsetValue = "UTF-16LE"; 
    w = new OutputStreamWriter(new FileOutputStream(new File(path)), Charset.forName(charsetValue))
    ...

and opening the file in notepad++ ?

**Comment by arnaud-web** [comment]
Hi,

Thanks for your responses.

Actually, I found a solution : 

`Writer writer = new OutputStreamWriter(new FileOutputStream(new File(path)), charset);

if (StandardCharsets.UTF_16LE.name().equals(this.preferences.getEncoding())) {
    writer.write("\uFEFF");
 }`

Not elegant but it works.

I close the topic.
