### ISSUE TITLE
Round the number and Trunkating string

### ISSUE THREAD

**Issue by nagraj321** [super-csv/super-csv#98]
I have the data in database with morethan 2 decimal points for the price, while preparing the csv file i need to round the price to max 2 decimal points.

Do we have the functionality to round the number using cell processors? If yes, please let me know how to achieve this?

Also i need to truncate the one of the column to send max of 60 chars and i'm using the CsvPreference.TAB_PREFERENCE to prepare the csv file. if that column contains the quotes (i.e. ") then it appending more quotes to the result.

Ex:
new NotNull(new Trim(new StrReplace("\\s+", " ", new Truncate(60))));

**Original String:** ED2013001 G001 16 POSITION (8+8) 19" WIDE REAR FEED PROVIDED ===> Length=61
**Expected Output:** ED2013001 G001 16 POSITION (8+8) 19" WIDE REAR FEED PROVIDE ====> Length=60
**Actual Output:** "ED2013001 G001 16 POSITION (8+8) 19"" WIDE REAR FEED PROVIDE" ====> Length=64

Thanks
Nagaraju

**Comment by kbilsted** [comment]
see https://super-csv.github.io/super-csv/cell_processors.html

there is no processor for rounding. If you write one you are more than welcome to send a PR. It really is very easy to write custom cell processors. See https://super-csv.github.io/super-csv/examples_new_cell_processor.html

**Comment by nagraj321** [comment]
[RoundNumber.txt](https://github.com/super-csv/super-csv/files/276983/RoundNumber.txt)
@kbilsted Attached file contains on how to implement the rounding the numbers using BigDecimal. Kindly check and let me know if i need to make any other changes..

E.g: new RoundNumber(2, BigDecimal.ROUND_HALF_UP);

**Comment by kbilsted** [comment]
I'd prefer to recieve it as a Pull request.

A few quick notes. Change the namespace, add the standard header, use the formatting as the rest of the code

**Comment by jamiebaggott** [comment]
While there may not be a `CellProcessor` specifically for rounding, the described function above is currently possible. `FmtNumber` can be used for rounding by passing in an appropriate `DecimalFormat` with a `RoundingMode`. If the number is required to be a `BigDecimal`, as it appears to be in the above text file, `ParseBigDecimal` can then be chained.

**Comment by kbilsted** [comment]
@jamiebaggott  nice. Feel free to update the documentation examples or the code documentation as a PR ;)
