### ISSUE TITLE
ParseBool does not support internationalization

### ISSUE THREAD

**Issue by rbotafogo** [super-csv/super-csv#99]
If I pass to ParseBool the faseValues = ["não"] this is not recognized as false.  It does not like the tilda on the a.

**Comment by ZioberMichal** [comment]
Hi @rbotafogo. 
Text "não" is not commonly used as `false` so by default it is not recognised. But you can extend false values using `ParseBool` constructor like below:
`ParseBool processor = new ParseBool(new String[]{"Sim"}, new String[]{"não"}, true);`

Please let me know whether it work for you.

**Comment by rbotafogo** [comment]
Michal,

If I use 'nao' as you suggested, everything works fine; however, 'não' does
not work.  I´m using supercsv inside a JRuby script, so this might be the
reason it is not working, but since 'nao' works fine I´m assuming that
there is something wrong with the '~' in supercsv. This is the result:

org.supercsv.exception.SuperCsvCellProcessorException: 'não' could not be
parsed as a Boolean
processor=org.jruby.proxy.org.supercsv.cellprocessor.ParseBool$Proxy3
context={lineNo=2, rowNo=2, columnNo=12, rowSource=[245, 5467.33456,
5467.33456, 12345678987654321, 3-5i, 300/2, 1234567898765432123456789,
0.12345, 0,12345, 123.456,07, t, não, verdadeiro, Paul]}
at
org.supercsv.cellprocessor.ParseBool.execute(org/supercsv/cellprocessor/ParseBool.java:340)
at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:497)
at RUBY.execute(T:/Rodrigo/Desenv/jCSV/lib/filters.rb:94)
at RUBY.block in
executeProcessors(T:/Rodrigo/Desenv/jCSV/lib/supercsv_interface.rb:122)
at
RUBY.each_with_index(uri:classloader:/jruby/java/java_ext/java.lang.rb:19)
at
RUBY.executeProcessors(T:/Rodrigo/Desenv/jCSV/lib/supercsv_interface.rb:96)
at RUBY.filter_input(T:/Rodrigo/Desenv/jCSV/lib/supercsv_interface.rb:220)
at RUBY.read(T:/Rodrigo/Desenv/jCSV/lib/supercsv_interface.rb:209)
at RUBY.read_chunk(T:/Rodrigo/Desenv/jCSV/lib/reader.rb:334)
at RUBY.read_chunk(T:/Rodrigo/Desenv/jCSV/lib/map_reader.rb:184)
at RUBY.parse_with_block(T:/Rodrigo/Desenv/jCSV/lib/reader.rb:99)
at RUBY.read(T:/Rodrigo/Desenv/jCSV/lib/map_reader.rb:86)
at T_3a_.Rodrigo.Desenv.jCSV.test.test_filters.block in
CSVTest(T:\Rodrigo\Desenv\jCSV\test\test_filters.rb:124)
at
org.jruby.RubyBasicObject.instance_exec(org/jruby/RubyBasicObject.java:1670)
at RUBY.block in test: CSV test should check all filters.
(D:/rbotafogo/cygwin2_4_0/jruby-9.0.5.0/lib/ruby/gems/shared/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413)
at
RUBY.run_test(D:/rbotafogo/cygwin2_4_0/jruby-9.0.5.0/lib/ruby/stdlib/test/unit/testcase.rb:697)
at
RUBY.run(D:/rbotafogo/cygwin2_4_0/jruby-9.0.5.0/lib/ruby/stdlib/test/unit/testcase.rb:437)
at
RUBY.run_test(D:/rbotafogo/cygwin2_4_0/jruby-9.0.5.0/lib/ruby/stdlib/test/unit/testsuite.rb:121)
at
RUBY.run(D:/rbotafogo/cygwin2_4_0/jruby-9.0.5.0/lib/ruby/stdlib/test/unit/testsuite.rb:53)
at
RUBY.run_test(D:/rbotafogo/cygwin2_4_0/jruby-9.0.5.0/lib/ruby/stdlib/test/unit/testsuite.rb:121)
at
RUBY.run(D:/rbotafogo/cygwin2_4_0/jruby-9.0.5.0/lib/ruby/stdlib/test/unit/testsuite.rb:53)
at
RUBY.run_suite(D:/rbotafogo/cygwin2_4_0/jruby-9.0.5.0/lib/ruby/stdlib/test/unit/ui/testrunnermediator.rb:65)
at RUBY.block in
run(D:/rbotafogo/cygwin2_4_0/jruby-9.0.5.0/lib/ruby/stdlib/test/unit/ui/testrunnermediator.rb:44)
at
RUBY.with_listener(D:/rbotafogo/cygwin2_4_0/jruby-9.0.5.0/lib/ruby/stdlib/test/unit/ui/testrunnermediator.rb:100)
at
RUBY.run(D:/rbotafogo/cygwin2_4_0/jruby-9.0.5.0/lib/ruby/stdlib/test/unit/ui/testrunnermediator.rb:40)
at
RUBY.start_mediator(D:/rbotafogo/cygwin2_4_0/jruby-9.0.5.0/lib/ruby/stdlib/test/unit/ui/testrunner.rb:40)
at
RUBY.start(D:/rbotafogo/cygwin2_4_0/jruby-9.0.5.0/lib/ruby/stdlib/test/unit/ui/testrunner.rb:25)
at
RUBY.run(D:/rbotafogo/cygwin2_4_0/jruby-9.0.5.0/lib/ruby/stdlib/test/unit/ui/testrunnerutilities.rb:24)
at RUBY.block in
run(D:/rbotafogo/cygwin2_4_0/jruby-9.0.5.0/lib/ruby/stdlib/test/unit/autorunner.rb:403)
at
RUBY.change_work_directory(D:/rbotafogo/cygwin2_4_0/jruby-9.0.5.0/lib/ruby/stdlib/test/unit/autorunner.rb:459)
at
RUBY.run(D:/rbotafogo/cygwin2_4_0/jruby-9.0.5.0/lib/ruby/stdlib/test/unit/autorunner.rb:402)
at
RUBY.run(D:/rbotafogo/cygwin2_4_0/jruby-9.0.5.0/lib/ruby/stdlib/test/unit/autorunner.rb:59)
at RUBY.block in
(root)(D:/rbotafogo/cygwin2_4_0/jruby-9.0.5.0/lib/ruby/stdlib/test/unit.rb:502)


2016-05-03 13:37 GMT-03:00 Michał Ziober <notifications@github.com>:

> Hi @rbotafogo <https://github.com/rbotafogo>.
> Text "não" is not commonly used as false so by default it is not
> recognised. But you can extend false values using ParseBool constructor
> like below:
> ParseBool processor = new ParseBool(new String[]{"Sim"}, new
> String[]{"não"}, true);
>
> Please let me know whether it work for you.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/super-csv/super-csv/issues/99#issuecomment-216588032>
>



-- 
Rodrigo Botafogo
Integrando TI ao seu negócio
21-3010-4802/11-3010-1802

**Comment by ZioberMichal** [comment]
I did some tests with characters-with-accents and all passed successfully. I tested this parser with 'não' and 'NÃO' values and in both cases it works like desired. Are you sure that you do not have any problems with handling UTF-8 characters on JRuby side?

**Comment by rbotafogo** [comment]
No, I´m not sure..... since it did pass your tests, then I should check the
way JRuby is passing the data.  Sorry for the trouble and thanks for your
support.  I´ll let you know when I have any news.

Thanks again!


2016-05-04 17:08 GMT-03:00 Michał Ziober <notifications@github.com>:

> I did some tests with characters-with-accents and all passed successfully.
> I tested this parser with 'não' and 'NÃO' values and in both cases it works
> like desired. Are you sure that you do not have any problems with handling
> UTF-8 characters on JRuby side?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/super-csv/super-csv/issues/99#issuecomment-216986126>
>



-- 
Rodrigo Botafogo
Integrando TI ao seu negócio
21-3010-4802/11-3010-1802

**Comment by rbotafogo** [comment]
Michal,

You are right (of course).  The script works on bash shell, but does not
work on Emacs.  So, it is a problem with the character encodings and not
with super_csv.

Again, thanks for your help.



2016-05-04 17:16 GMT-03:00 Rodrigo Botafogo <rodrigo.a.botafogo@gmail.com>:

> No, I´m not sure..... since it did pass your tests, then I should check
> the way JRuby is passing the data.  Sorry for the trouble and thanks for
> your support.  I´ll let you know when I have any news.
>
> Thanks again!
>
>
> 2016-05-04 17:08 GMT-03:00 Michał Ziober <notifications@github.com>:
>
>> I did some tests with characters-with-accents and all passed
>> successfully. I tested this parser with 'não' and 'NÃO' values and in both
>> cases it works like desired. Are you sure that you do not have any problems
>> with handling UTF-8 characters on JRuby side?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/super-csv/super-csv/issues/99#issuecomment-216986126>
>>
>
>
>
> --
> Rodrigo Botafogo
> Integrando TI ao seu negócio
> 21-3010-4802/11-3010-1802
>



-- 
Rodrigo Botafogo
Integrando TI ao seu negócio
21-3010-4802/11-3010-1802

**Comment by ZioberMichal** [comment]
No problem. I glad I could help.
